name: Release GO binaries

on:
  release:
    types: [published]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows]
        goarch: ["386", amd64, arm64, arm]
        exclude:
        - goarch: arm64
          goos: windows
        - goarch: arm
          goos: windows
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - uses: wangyoucao577/go-release-action@2ac3035fa4c4feed6a8272ce278b0577b93cf8e5 # v1.40
      with:
        github_token: ${{ secrets.GIT_HUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.25.0"
        binary_name: "gluetun-qbittorrent-port-manager"
        ldflags: "-s -w"
        extra_files: README.md
        retry: 10
        overwrite: true
        release_name: ${{ github.event.release.tag_name }}
        pre_command: sed -i 's/{{RELEASE_TAG}}/${{ github.event.release.tag_name }}/g' modules/files.go # Replace release variable with the name of this release